apiVersion: v1
kind: ServiceAccount
metadata:
  name: travelmate-sa
  namespace: travelmate
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: travelmate-role
  namespace: travelmate
rules:
  - apiGroups: [""]
    resources: ["configmaps", "secrets"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: travelmate-role-binding
  namespace: travelmate
subjects:
  - kind: ServiceAccount
    name: travelmate-sa
    namespace: travelmate
roleRef:
  kind: Role
  name: travelmate-role
  apiGroup: rbac.authorization.k8s.io
